/**
 * Regenerates packages/core/src/config/abi.ts from the compiled Foundry
 * artifacts. Run via `bun run abi`; `bun run abi:check` runs it and fails if
 * the result differs from what is committed (INV-18).
 */
const CONTRACTS = [
  { name: "TapPay", exportName: "tapPayAbi" },
  { name: "TapMerchantRegistrar", exportName: "tapMerchantRegistrarAbi" },
] as const;

const OUTPUT = "packages/core/src/config/abi.ts";

async function readAbi(name: string): Promise<unknown[]> {
  const path = `contracts/out/${name}.sol/${name}.json`;
  const file = Bun.file(path);

  if (!(await file.exists())) {
    throw new Error(`Missing artifact ${path}. Run \`cd contracts && forge build\` first.`);
  }

  const artifact = (await file.json()) as { abi?: unknown[] };
  if (!Array.isArray(artifact.abi)) throw new Error(`Artifact ${path} has no abi array`);
  return artifact.abi;
}

const sections: string[] = [
  "// GENERATED by scripts/generate-abi.ts. Do not edit by hand.",
  "// Regenerate with `bun run abi` after changing a contract.",
];

for (const { name, exportName } of CONTRACTS) {
  const abi = await readAbi(name);
  sections.push(`export const ${exportName} = ${JSON.stringify(abi, null, 2)} as const;`);
}

await Bun.write(OUTPUT, `${sections.join("\n\n")}\n`);

// Hand the formatting to Biome so the generated file matches the repo style
// and regenerating is byte-identical, which is what abi:check compares.
const formatted = Bun.spawnSync(["bunx", "biome", "format", "--write", OUTPUT], {
  stdout: "pipe",
  stderr: "pipe",
});
if (formatted.exitCode !== 0) {
  throw new Error(`biome format failed: ${formatted.stderr.toString()}`);
}

console.log(`Wrote ${OUTPUT} (${CONTRACTS.map((c) => c.name).join(", ")})`);
